export const languageNames: { [key: string]: string } = {
    en: "English",
    pt: "Portuguese",
    es: "Spanish",
    ru: "Russian",
    tr: "Turkish",
    fr: "French",
    de: "German",
    it: "Italian",
    nl: "Dutch",
    pl: "Polish",
    uk: "Ukrainian",
    ar: "Arabic",
    bg: "Bulgarian",
    cs: "Czech",
    da: "Danish",
    el: "Greek",
    et: "Estonian",
    fi: "Finnish",
    he: "Hebrew",
    hi: "Hindi",
    hr: "Croatian",
    hu: "Hungarian",
    id: "Indonesian",
    ja: "Japanese",
    ko: "Korean",
    lt: "Lithuanian",
    lv: "Latvian",
    ms: "Malay",
    no: "Norwegian",
    ro: "Romanian",
    sk: "Slovak",
    sl: "Slovenian",
    sv: "Swedish",
    th: "Thai",
    vi: "Vietnamese",
    zh: "Chinese",
    fa: "Persian",
    bn: "Bengali",
    ca: "Catalan",
    eu: "Basque",
    gl: "Galician",
    "zh-Latn": "Chinese (Latin)",
    "ja-Latn": "Japanese (Latin)",
    "ru-Latn": "Russian (Latin)",
    "bg-Latn": "Bulgarian (Latin)",
    ceb: "Cebuano",
    hmn: "Hmong",
    uz: "Uzbek",
    la: "Latin"
} as const;
